# Generated by Django 5.0.1 on 2024-01-24 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotelapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='check_in',
            new_name='check_in_date',
        ),
        migrations.RenameField(
            model_name='booking',
            old_name='check_out',
            new_name='check_out_date',
        ),
        migrations.AddField(
            model_name='booking',
            name='phone_number',
            field=models.CharField(default='', max_length=10),
        ),
    ]
