# Generated by Django 5.0.1 on 2024-01-24 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotelapp', '0002_rename_check_in_booking_check_in_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='room_type',
            field=models.CharField(choices=[('standard', 'ธรรมดา'), ('superior', 'ซูพีเรียร์'), ('deluxe', 'ดีลักซ์')], max_length=20),
        ),
    ]
